# Generated by Django 3.2.5 on 2021-08-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210827_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testslot',
            name='time_slot',
            field=models.CharField(choices=[('M', 'Morning'), ('E', 'Evening')], max_length=10, null=True),
        ),
    ]
