# Generated by Django 3.2.5 on 2021-08-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_testslot_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestattempt',
            name='is_attempted',
            field=models.BooleanField(default=False),
        ),
    ]
