# Generated by Django 3.2.5 on 2021-08-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_usertestattempt_is_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
